apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: api-conversor-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-conversor
  template:
    metadata:
      labels:
        app: api-conversor
    spec:
      containers:
        - name: api-conversor
          image: typhanael/conversor-temperatura:v1
          ports:
            - containerPort: 8080
